# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 70, 721, 321))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.button23 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button23.setText("")
        self.button23.setObjectName("button23")
        self.gridLayout.addWidget(self.button23, 1, 2, 1, 1)
        self.button86 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button86.setText("")
        self.button86.setObjectName("button86")
        self.gridLayout.addWidget(self.button86, 7, 5, 1, 1)
        self.button25 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button25.setText("")
        self.button25.setObjectName("button25")
        self.gridLayout.addWidget(self.button25, 1, 4, 1, 1)
        self.button24 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button24.setText("")
        self.button24.setObjectName("button24")
        self.gridLayout.addWidget(self.button24, 1, 3, 1, 1)
        self.button84 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button84.setText("")
        self.button84.setObjectName("button84")
        self.gridLayout.addWidget(self.button84, 7, 3, 1, 1)
        self.button12 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button12.setText("")
        self.button12.setObjectName("button12")
        self.gridLayout.addWidget(self.button12, 0, 1, 1, 1)
        self.button41 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button41.setText("")
        self.button41.setObjectName("button41")
        self.gridLayout.addWidget(self.button41, 3, 0, 1, 1)
        self.button51 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button51.setText("")
        self.button51.setObjectName("button51")
        self.gridLayout.addWidget(self.button51, 4, 0, 1, 1)
        self.button31 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button31.setText("")
        self.button31.setObjectName("button31")
        self.gridLayout.addWidget(self.button31, 2, 0, 1, 1)
        self.button21 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button21.setText("")
        self.button21.setObjectName("button21")
        self.gridLayout.addWidget(self.button21, 1, 0, 1, 1)
        self.button61 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button61.setText("")
        self.button61.setObjectName("button61")
        self.gridLayout.addWidget(self.button61, 5, 0, 1, 1)
        self.button71 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button71.setText("")
        self.button71.setObjectName("button71")
        self.gridLayout.addWidget(self.button71, 6, 0, 1, 1)
        self.button82 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button82.setText("")
        self.button82.setObjectName("button82")
        self.gridLayout.addWidget(self.button82, 7, 1, 1, 1)
        self.button11 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button11.setEnabled(False)
        self.button11.setText("")
        self.button11.setObjectName("button11")
        self.gridLayout.addWidget(self.button11, 0, 0, 1, 1)
        self.button22 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button22.setText("")
        self.button22.setObjectName("button22")
        self.gridLayout.addWidget(self.button22, 1, 1, 1, 1)
        self.button27 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button27.setText("")
        self.button27.setObjectName("button27")
        self.gridLayout.addWidget(self.button27, 1, 6, 1, 1)
        self.button26 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button26.setText("")
        self.button26.setObjectName("button26")
        self.gridLayout.addWidget(self.button26, 1, 5, 1, 1)
        self.button28 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button28.setText("")
        self.button28.setObjectName("button28")
        self.gridLayout.addWidget(self.button28, 1, 7, 1, 1)
        self.button38 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button38.setText("")
        self.button38.setObjectName("button38")
        self.gridLayout.addWidget(self.button38, 2, 7, 1, 1)
        self.button81 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button81.setText("")
        self.button81.setObjectName("button81")
        self.gridLayout.addWidget(self.button81, 7, 0, 1, 1)
        self.button13 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button13.setText("")
        self.button13.setObjectName("button13")
        self.gridLayout.addWidget(self.button13, 0, 2, 1, 1)
        self.button88 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button88.setText("")
        self.button88.setObjectName("button88")
        self.gridLayout.addWidget(self.button88, 7, 7, 1, 1)
        self.button83 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button83.setText("")
        self.button83.setObjectName("button83")
        self.gridLayout.addWidget(self.button83, 7, 2, 1, 1)
        self.button85 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button85.setText("")
        self.button85.setObjectName("button85")
        self.gridLayout.addWidget(self.button85, 7, 4, 1, 1)
        self.button14 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button14.setText("")
        self.button14.setObjectName("button14")
        self.gridLayout.addWidget(self.button14, 0, 3, 1, 1)
        self.button16 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button16.setText("")
        self.button16.setObjectName("button16")
        self.gridLayout.addWidget(self.button16, 0, 5, 1, 1)
        self.button87 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button87.setText("")
        self.button87.setObjectName("button87")
        self.gridLayout.addWidget(self.button87, 7, 6, 1, 1)
        self.button58 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button58.setText("")
        self.button58.setObjectName("button58")
        self.gridLayout.addWidget(self.button58, 4, 7, 1, 1)
        self.button15 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button15.setText("")
        self.button15.setObjectName("button15")
        self.gridLayout.addWidget(self.button15, 0, 4, 1, 1)
        self.button18 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button18.setText("")
        self.button18.setObjectName("button18")
        self.gridLayout.addWidget(self.button18, 0, 7, 1, 1)
        self.button17 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button17.setText("")
        self.button17.setObjectName("button17")
        self.gridLayout.addWidget(self.button17, 0, 6, 1, 1)
        self.button68 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button68.setText("")
        self.button68.setObjectName("button68")
        self.gridLayout.addWidget(self.button68, 5, 7, 1, 1)
        self.button48 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button48.setText("")
        self.button48.setObjectName("button48")
        self.gridLayout.addWidget(self.button48, 3, 7, 1, 1)
        self.button77 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button77.setText("")
        self.button77.setObjectName("button77")
        self.gridLayout.addWidget(self.button77, 6, 6, 1, 1)
        self.button78 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button78.setText("")
        self.button78.setObjectName("button78")
        self.gridLayout.addWidget(self.button78, 6, 7, 1, 1)
        self.button52 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button52.setText("")
        self.button52.setObjectName("button52")
        self.gridLayout.addWidget(self.button52, 4, 1, 1, 1)
        self.button42 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button42.setText("")
        self.button42.setObjectName("button42")
        self.gridLayout.addWidget(self.button42, 3, 1, 1, 1)
        self.button32 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button32.setText("")
        self.button32.setObjectName("button32")
        self.gridLayout.addWidget(self.button32, 2, 1, 1, 1)
        self.button62 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button62.setText("")
        self.button62.setObjectName("button62")
        self.gridLayout.addWidget(self.button62, 5, 1, 1, 1)
        self.button72 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button72.setText("")
        self.button72.setObjectName("button72")
        self.gridLayout.addWidget(self.button72, 6, 1, 1, 1)
        self.button73 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button73.setText("")
        self.button73.setObjectName("button73")
        self.gridLayout.addWidget(self.button73, 6, 2, 1, 1)
        self.button33 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button33.setText("")
        self.button33.setObjectName("button33")
        self.gridLayout.addWidget(self.button33, 2, 2, 1, 1)
        self.button43 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button43.setText("")
        self.button43.setObjectName("button43")
        self.gridLayout.addWidget(self.button43, 3, 2, 1, 1)
        self.button53 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button53.setText("")
        self.button53.setObjectName("button53")
        self.gridLayout.addWidget(self.button53, 4, 2, 1, 1)
        self.button34 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button34.setText("")
        self.button34.setObjectName("button34")
        self.gridLayout.addWidget(self.button34, 2, 3, 1, 1)
        self.button63 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button63.setText("")
        self.button63.setObjectName("button63")
        self.gridLayout.addWidget(self.button63, 5, 2, 1, 1)
        self.button35 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button35.setText("")
        self.button35.setObjectName("button35")
        self.gridLayout.addWidget(self.button35, 2, 4, 1, 1)
        self.button36 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button36.setText("")
        self.button36.setObjectName("button36")
        self.gridLayout.addWidget(self.button36, 2, 5, 1, 1)
        self.button37 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button37.setText("")
        self.button37.setObjectName("button37")
        self.gridLayout.addWidget(self.button37, 2, 6, 1, 1)
        self.button44 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button44.setText("")
        self.button44.setObjectName("button44")
        self.gridLayout.addWidget(self.button44, 3, 3, 1, 1)
        self.button54 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button54.setText("")
        self.button54.setObjectName("button54")
        self.gridLayout.addWidget(self.button54, 4, 3, 1, 1)
        self.button64 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button64.setText("")
        self.button64.setObjectName("button64")
        self.gridLayout.addWidget(self.button64, 5, 3, 1, 1)
        self.button74 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button74.setText("")
        self.button74.setObjectName("button74")
        self.gridLayout.addWidget(self.button74, 6, 3, 1, 1)
        self.button45 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button45.setText("")
        self.button45.setObjectName("button45")
        self.gridLayout.addWidget(self.button45, 3, 4, 1, 1)
        self.button55 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button55.setText("")
        self.button55.setObjectName("button55")
        self.gridLayout.addWidget(self.button55, 4, 4, 1, 1)
        self.button65 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button65.setText("")
        self.button65.setObjectName("button65")
        self.gridLayout.addWidget(self.button65, 5, 4, 1, 1)
        self.button75 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button75.setText("")
        self.button75.setObjectName("button75")
        self.gridLayout.addWidget(self.button75, 6, 4, 1, 1)
        self.button46 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button46.setText("")
        self.button46.setObjectName("button46")
        self.gridLayout.addWidget(self.button46, 3, 5, 1, 1)
        self.button47 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button47.setText("")
        self.button47.setObjectName("button47")
        self.gridLayout.addWidget(self.button47, 3, 6, 1, 1)
        self.button57 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button57.setText("")
        self.button57.setObjectName("button57")
        self.gridLayout.addWidget(self.button57, 4, 6, 1, 1)
        self.button67 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button67.setText("")
        self.button67.setObjectName("button67")
        self.gridLayout.addWidget(self.button67, 5, 6, 1, 1)
        self.button56 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button56.setText("")
        self.button56.setObjectName("button56")
        self.gridLayout.addWidget(self.button56, 4, 5, 1, 1)
        self.button66 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button66.setText("")
        self.button66.setObjectName("button66")
        self.gridLayout.addWidget(self.button66, 5, 5, 1, 1)
        self.button76 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button76.setText("")
        self.button76.setObjectName("button76")
        self.gridLayout.addWidget(self.button76, 6, 5, 1, 1)
        self.buttonPasar = QtWidgets.QPushButton(self.centralwidget)
        self.buttonPasar.setGeometry(QtCore.QRect(290, 500, 80, 23))
        self.buttonPasar.setObjectName("buttonPasar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.buttonPasar.setText(_translate("MainWindow", "Pasar Turno"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

